export const ADD_ITEM = 'ADD_ITEM';
export const ITEM_LOADING_START = 'ITEM_LOADING_START';
export const ITEM_LOADING_FAIL = 'ITEM_LOADING_FAIL';
export const ITEM_LOADING_END = 'ITEM_LOADING_FAIL';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const MOBILE_SHOW_ITEM = 'MOBILE_SHOW_ITEM';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';